FROM debian:wheezy
ENV container docker
RUN echo 'deb http://deb.debian.org/debian wheezy-backports main' > /etc/apt/sources.list.d/backports.list
# Don't start any optional services except for the few we need. 
RUN apt-get update
RUN apt-get -y install systemd
RUN find /etc/systemd/system \
         /lib/systemd/system \
         -path '*.wants/*' \
         -not -name '*journald*' \
         -not -name '*systemd-tmpfiles*' \
         -not -name '*systemd-user-sessions*' \
         -exec rm \{} \;
#RUN systemctl set-default multi-user.target
CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]
#
RUN apt-get update && apt-get install -y openssh-server iproute2 devscripts \
	equivs screen less wget vim libevent-2.0-5 libevent-core-2.0-5 \
	libunbound-dev libevent-dev ldnsutils libldns-dev gdb
RUN rm -rf /etc/ssh/ssh_host*
#
#
RUN ssh-keygen -b 1024 -t rsa -f /etc/ssh/ssh_host_key
RUN ssh-keygen -b 1024 -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -b 1024 -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN mkdir /root/.ssh && \
  touch /root/.ssh/authorized_keys && \
  chmod 700 /root/.ssh && \
  chmod 600 /root/.ssh/authorized_keys
# copy the file /root/.ssh/authorized_keys to cwd
ADD authorized_keys /root/.ssh/authorized_keys
RUN chmod 400 /root/.ssh/authorized_keys
RUN chown -R root:root /root/.ssh
RUN sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
RUN sed -i 's/UsePAM\syes/UsePAM no/' /etc/ssh/sshd_config
RUN echo "UseDNS no" >> /etc/ssh/sshd_config
RUN echo 'export EDITOR=vim' >> /root/.bash_profile
RUN sed -i '/StrictModes/d' /etc/ssh/sshd_config
RUN echo "StrictModes no" >> /etc/ssh/sshd_config
RUN wget  -O libreswan-debian-control https://raw.githubusercontent.com/libreswan/libreswan/master/debian/control
#RUN 'echo Y | mk-build-deps --install libreswan-debian-control'
STOPSIGNAL SIGRTMIN+3 
